language: ruby
rvm:
- 2.5.8
before_install:
- gem update --system
- gem install bundler
notifications:
  email: false
  slack:
    on_success: change
    on_failure: always
    on_pull_requests: false
    rooms:
      - secure: kRh0VhfoeS19wDeckS1go0272Y994UXPu59/Gmbc5APfEhM3UmqV84bSaJSN+gOqnFh5yJvUTdlj9dOM7CjtvcjUFSrRx1SXhhMDDPB9+iZCSQ7HfGljob4cLP6N26UZicZ2UtzujuDu1OpmhKqoosepzIRBaFM8i3Wa6uLtB6H+APFLtiuVNIpu/YaQIjrOjylZeafX7Usi5dWrs8cxtTJmwHT7xyTNm8nt5gQx+Gr5dFT6LAEsdfZBqSVK4fGipraLG9nb3jpRmWr5oRnGJ/0+DSUJKcv5XuzkCdbIVdnXxARXL1V32SVJFF1sfzE34Co5XriLqVF0WoIN+WEpPE4Qu7YR5SvwsXuE2/S4fW/cZ7sla1q28EKxN13IC5Lkn3VaRxfy4gn0iG9oOpEbmu9sHwEvFWuWxuU0bjIKsqzzAv3Yc1WLnyODxYpxEDoWZESYat3dB514yPmH10EVxlIurxApsDPnVGL31Akvr6/UOC43z6rP6YWrBmExc2T3QqpI1+iHaMyLaA4Y2sbfL6DRusmM6RQgVp3jJgJPT7ko8OMPzTzE0/X0NTtOHH8BS1YfkfGeYxts1CElZIol85EwFNwVnsoCMQohC2RccjFhxdfXCjusagd+7Sfh8sPz5R5BUE2kuJDUAZhERKG0axzfpr3xCWPNTfFsSqv3Zjg=
